server:
  port: 8080
#spring:
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      server-addr: 192.168.145.130:8848
#    gateway:
#      routes:
#        - id: item-service
#          uri: lb://item-service
#          predicates:
#            - Path=/item/**,/search/**
#
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**,/addresses/**
#
#        - id: pay-service
#          uri: lb://pay-service
#          predicates:
#            - Path=/pay-orders/**
#
#        - id: trade-service
#          uri: lb://trade-service
#          predicates:
#            - Path=/orders/**
#      default-filters:
#        - AddRequestHeader=hi,hi
#        - PrintAny=1,2
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi